# Screen dimensions
SCREEN_WIDTH = 500
SCREEN_HEIGHT = 500

# Font Properties
FONT_COLOR = (255, 255, 255)
GAME_FONT_SIZE = 10
MENU_FONT_SIZE = 15
MENU_HISCORE_SIZE = 10

# Player properties
PLAYER_SIZE = 5
PLAYER_SPEED_X = 200
PLAYER_COLOR = "blue"

# Projectile properties
PROJECTILE_SPEED = 200
PROJECTILE_COOLDOWN = 1000  # milliseconds
PROJECTILE_SIZE = 3
PROJECTILE_COLOR = "green"

# Enemy properties
ENEMY_SIZE = 10
ENEMY_SPEED_X = 50
ENEMY_SPEED_Y = 400
ENEMY_COLUMNS = 6
ENEMY_ROWS = 3
ENEMY_SPACING = 60
ENEMY_COLOR = "black"
ENEMY_PROJECTILE_COLOR = "red"
ENEMY_PROJECTILE_COOLDOWN = 500
